CREATE TABLE IF NOT EXISTS boards (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(150) NOT NULL,
	urlid VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	type INT(1) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bans (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ip VARCHAR(50) NOT NULL,
	reason VARCHAR(3500),
	date DATETIME NOT NULL DEFAULT NOW(),
	expires DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS adminaction (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	accountid INT(6) NOT NULL,
	info VARCHAR(3500),
	date DATETIME NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;